# ===== Stage 1 =====
FROM node:18 AS builder

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

# ❌ XÓA DÒNG NÀY
# RUN npm run build


# ===== Stage 2 =====
FROM node:18-alpine

WORKDIR /app

COPY --from=builder /app ./

EXPOSE 3000

CMD ["npm", "start"]